### ISSUE TITLE
Can't generate sdk for the latest model (version 4.3.8)

### ISSUE THREAD

**Issue by andrexus** [imjoey/ovirt-engine-sdk-go#99]
Exception stack trace
```
[INFO] --- exec-maven-plugin:1.2.1:java (generate-code) @ go-sdk ---
ERROR Main - Error while executing the "run" method of tool class "org.ovirt.sdk.go.Tool".
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ovirt.api.metamodel.tool.Main.main(Main.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.ovirt.api.metamodel.concepts.ArrayExpression cannot be cast to org.ovirt.api.metamodel.analyzer.MethodExpression
	at org.ovirt.api.metamodel.analyzer.InputDetailAnalyzer.removePrefix(InputDetailAnalyzer.java:87)
```

**Comment by mwperina** [comment]
@machacekondra

**Comment by imjoey** [comment]
@andrexus Please update the latest code first, with issue #100 fixed .  After updating, the generator with the model 4.3.8 and metamodel 1.3.0 is works for me. If there still has problems, please offer your metamodel version and the root pom file.

**Comment by imjoey** [comment]
@andrexus  I had just re-produce this error. Maybe you ran the `mvn package` under the `./sdk` subdirectory. While `mvn package` command must be running under the root `./` directory.

**Comment by imjoey** [comment]
@andrexus As mentioned above, this is actually not a bug. Close it now. If you still have problems, please be free to reopen it.
